- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    homebrew_taps:
      - altkatz/gcc_cross_compilers
      - aspnet/dnx
      - caskroom/cask
      - fnichol/dvm
      - homebrew/binary
      - homebrew/dupes
      - homebrew/science
      - jubatus/jubatus
      - motemen/ghq
      - tcnksm/ghr
      - cubicdaiya/nginx-build
      - tkengo/highway
    homebrew_packages:
      - { name: ansible }
      - { name: readline }
      - { name: openssl }
      - { name: sshrc }
      - { name: ssh-copy-id }
      - { name: iproute2mac }
      - { name: python }
      - { name: python3 }
      - { name: pyenv }
      - { name: go }
      - { name: glide }
      - { name: haskell-stack }
      - { name: git }
      - { name: git-secrets }
      - { name: carthage}
      - { name: tig}
      - { name: zsh }
      - { name: wget }
      - { name: curl }
      - { name: pt }
      - { name: highway }
      - { name: nkf }
      - { name: cmake }
      - { name: tree }
      - { name: jq }
      - { name: peco }
      - { name: pandoc }
      - { name: ghq}
      - { name: rbenv }
      - { name: ruby-build }
      - { name: plenv }
      - { name: perl-build }
      - { name: multirust }
      - { name: dmd }
      - { name: mono }
      - { name: sbt }
      - { name: mysql }
      - { name: sqlite }
      - { name: redis }
      - { name: packer}
      - { name: terraform }
      - { name: consul }
      - { name: vault }
      - { name: nomad }
      - { name: otto }
      - { name: highlight }
      - { name: awscli }
      - { name: nginx }
      - { name: nginx-build }
      - { name: imagemagick }
      - { name: graphviz }
      - { name: ffmpeg }
      - { name: jubatus }
      - { name: mongodb }
    homebrew_cask_packages:
      - { name: appcleaner }
      - { name: iterm2 }
      - { name: macdown }
      - { name: mysqlworkbench}
      - { name: sequel-pro }
      - { name: psequel}
      - { name: qlcolorcode }
      - { name: qlstephen }
      - { name: qlmarkdown }
      - { name: quicklook-json }
      - { name: qlprettypatch }
      - { name: quicklook-csv }
      - { name: betterzipql }
      - { name: qlimagesize }
      - { name: webpquicklook }
      - { name: suspicious-package }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew のアップデート
      homebrew: update_homebrew=yes

    - name: homebrew cask のアップデート
      homebrew: name=brew-cask state=latest

    - name: homebrewパッケージをインストール
      homebrew: name={{ item.name }} state="latest"
      with_items: homebrew_packages

    - name: homebrew caskパッケージのインストール
      homebrew_cask: name={{ item.name }} state="present"
      with_items: homebrew_cask_packages
